// Generated by CoffeeScript 1.6.1
(function() {
  var Tarsus;

  Tarsus = function(Backbone) {
    "use strict";    Tarsus = {};
    if (typeof exports !== "undefined" && exports !== null) {
      Tarsus = exports;
    }
    Tarsus.VERSION = "0.0.1";
    Tarsus.Views = {};
    Tarsus.Views.Bootstrap = {};
    return Tarsus;
  };

  Tarsus(Backbone);

}).call(this);
