// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Tarsus.Views.Bootstrap.Carousel = (function(_super) {

    __extends(Carousel, _super);

    function Carousel() {
      return Carousel.__super__.constructor.apply(this, arguments);
    }

    return Carousel;

  })(Backbone.View);

}).call(this);
