// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Tarsus.Views.Bootstrap.Modal = (function(_super) {

    __extends(Modal, _super);

    function Modal() {
      return Modal.__super__.constructor.apply(this, arguments);
    }

    Modal.prototype.tagName = 'div';

    Modal.prototype.className = 'modal hide fade';

    Modal.prototype.attributes = {
      tabindex: -1,
      style: 'outline: 0;'
    };

    Modal.prototype.events = {
      'shown': 'shown',
      'hidden': 'hidden'
    };

    Modal.prototype.defaults = {
      bootstrap: {
        backdrop: true,
        keyboard: true,
        show: false,
        remote: false
      },
      noCloseButton: false
    };

    Modal.prototype.initialize = function(options) {
      _.bindAll(this);
      return this.options = _.extend(this.defaults, options);
    };

    Modal.prototype.render = function() {
      var body, footer, footerContainer, header, headerContainer, model;
      if (this.model === Backbone.Model) {
        model = this.model.attributes;
      }
      header = this.header();
      footer = this.footer();
      body = Backbone.$('<div class="modal-body"></div>');
      body.append(this.template(model));
      if (header != null) {
        headerContainer = this.headerContainer();
        if (!this.options.noCloseButton) {
          headerContainer.append(this.closeButton());
        }
        headerContainer.append(header);
        this.$el.append(headerContainer);
      }
      this.$el.append(body);
      if (footer != null) {
        footerContainer = this.footerContainer();
        footerContainer.append(footer);
        this.$el.append(footerContainer);
      }
      this.$el.modal(this.options.bootstrap);
      return this;
    };

    Modal.prototype.show = function() {
      this.$el.modal('show');
      this.trigger('tarsus:modal:show');
      return this;
    };

    Modal.prototype.shown = function() {};

    Modal.prototype.hide = function() {
      this.$el.modal('hide');
      this.trigger('tarsus:modal:hide');
      return this;
    };

    Modal.prototype.hidden = function() {};

    Modal.prototype.toggle = function() {
      this.$el.modal('toggle');
      this.trigger('tarsus:modal:toggle');
      return this;
    };

    Modal.prototype.headerContainer = function() {
      return Backbone.$('<div class="modal-header"></div>');
    };

    Modal.prototype.header = function() {
      if (this.options.title != null) {
        return Backbone.$('<h3>' + this.options.title + '</h3>');
      }
    };

    Modal.prototype.closeButton = function() {
      return Backbone.$('<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>');
    };

    Modal.prototype.footerContainer = function() {
      return Backbone.$('<div class="modal-footer"></div>');
    };

    Modal.prototype.footer = function() {};

    return Modal;

  })(Backbone.View);

}).call(this);
