// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Tarsus.Views.Bootstrap.Popover = (function(_super) {

    __extends(Popover, _super);

    function Popover() {
      return Popover.__super__.constructor.apply(this, arguments);
    }

    Popover.prototype.tagName = 'a';

    Popover.prototype.className = 'btn';

    Popover.prototype.attributes = {
      href: '#'
    };

    Popover.prototype.defaults = {
      bootstrap: {
        animation: true,
        html: false,
        placement: 'top',
        selector: false,
        trigger: 'hover focus',
        delay: 0,
        container: false,
        title: null,
        content: null
      },
      text: null
    };

    Popover.prototype.initialize = function(options) {
      _.bindAll(this);
      return this.options = _.extend(this.defaults, options);
    };

    Popover.prototype.render = function() {
      this.$el.text(this.options.text);
      this.$el.popover(this.options.bootstrap);
      return this;
    };

    Popover.prototype.show = function() {
      this.$el.popover('show');
      this.trigger('tarsus:popover:show');
      return this;
    };

    Popover.prototype.hide = function() {
      this.$el.popover('hide');
      this.trigger('tarsus:popover:hide');
      return this;
    };

    Popover.prototype.toggle = function() {
      this.$el.popover('toggle');
      this.trigger('tarsus:popover:toggle');
      return this;
    };

    Popover.prototype.destroy = function() {
      this.$el.popover('destroy');
      this.trigger('tarsus:popover:destroy');
      return this;
    };

    return Popover;

  })(Backbone.View);

}).call(this);
